#!/bin/python3

import math
import os
import random
import re
import sys


q = int(input())
final = "0"
for q_itr in range(0,q):
    xyz = input().split()

    x = int(xyz[0])

    y = int(xyz[1])

    z = int(xyz[2])

    a = abs(z-x) 
    b  = abs(z-y)
    if a <b: 
        final =  "Cat A"
        print (final)
    elif a==b:
        final = "Mouse C"
        print (final)
    else :
        if a>b:
            final = "Cat B"
            print (final)
