#!/bin/python3

import math
import os
import random
import re
import sys



x1V1X2V2 = input().split()

x1 = int(x1V1X2V2[0])

v1 = int(x1V1X2V2[1])

x2 = int(x1V1X2V2[2])

v2 = int(x1V1X2V2[3])
ans ="NO"
for i in range(1,10000):
    jumpx1 = x1+(i*v1)
    jumpx2 = x2+(i*v2)
    if jumpx1==jumpx2:
        ans = "YES"
    
if ans== "YES":
    a =ans
else:
    a = "NO"

print(a)
